name: Debug pnpm and Juno action

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node

      - name: Deploy to Juno
        uses: junobuild/juno-action@9712626cb52c74de794d51633b24f242e8f0b18f
        with:
          args: deploy
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
